version: '3'
services:
   puppeteer:
     image: 'ghcr.io/puppeteer/puppeteer:latest'
     platform: linux/amd64
     cap_add:
       - SYS_ADMIN
   app:
    build: "."
    ports:
      - "6000:4121"
    

