
name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIAU6GDW6OC6BBHDRW5
        aws-secret-access-key: 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
        aws-region: ap-south-1
    
    - name: Login to AWS ECR
      run: |
        aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 123456789012.dkr.ecr.ap-south-1.amazonaws.com

    - name: Build the Docker image
      run: docker build -t server .

    - name: Tag the Docker image
      run: docker tag server:latest 339712865157.dkr.ecr.ap-south-1.amazonaws.com/server:latest

    - name: Push the Docker image
      run: docker push 339712865157.dkr.ecr.ap-south-1.amazonaws.com/server

